### ISSUE TITLE
Project fails to build due to isnan issue in MADP

### ISSUE THREAD

**Issue by fpetric** [laurimi/npgi#1]
The project fails to build if MADP is downloaded automatically, with this error trace:
`prob.h:531:30: error: 'isnan' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
                     if( isnan( _p[i] ) )
`
This is a common issue when the older code is not up to new C++ standards, and the issue was resolved in the MADP with the latest commit (MADPToolbox/MADP@a6c1bb7), however this project downloads an earlier release of the MADP.

A dirty hack is to edit MADP source files after the download, however the best solution would be to autodownload the latest version od MADP code. At the very least, this information could be added to README of this project.

**Comment by laurimi** [comment]
Thanks, I updated the project to download a version of MADP that should compile with newer compilers.
